"""
Django settings for config project.

Generated by 'django-admin startproject' using Django.
"""

from pathlib import Path
import os
from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


SECRET_KEY = 'django-insecure-+aepa2=mqg(x)=7r^(ml^n#1wt!(i81)177hdvgk7uwiuld773'

DEBUG = True

ALLOWED_HOSTS = []


INSTALLED_APPS = [
    'pages',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        # Это позволяет Django искать шаблоны внутри приложений
        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Настройки e-mail рассылки
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.getenv('MAIL_HOST', 'smtp.mail.ru')
EMAIL_PORT = int(os.getenv('MAIL_PORT', 465))

EMAIL_USE_SSL = os.getenv('MAIL_ENCRYPTION', 'ssl') == 'ssl'
EMAIL_USE_TLS = os.getenv('MAIL_ENCRYPTION', '') == 'tls'

EMAIL_HOST_USER = os.getenv('MAIL_USERNAME')
EMAIL_HOST_PASSWORD = os.getenv('MAIL_PASSWORD')

DEFAULT_FROM_EMAIL = os.getenv('MAIL_FROM_ADDRESS', EMAIL_HOST_USER)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

MAIL_FROM_NAME = os.getenv('MAIL_FROM_NAME', 'News Portal')
MODERATOR_EMAIL = os.getenv('MODERATOR_EMAIL', EMAIL_HOST_USER)